"use strict";

async function createNewChat() {
  try {
    if (typeof window.createServerChat === 'function') {
      const serverId = await window.createServerChat();
      if (serverId) {
        currentChatID = serverId;
        history.pushState({}, '', `?chatid=${serverId}`);
        try {
          const allChats = JSON.parse(localStorage.getItem('allChats') || '{}');
          allChats[serverId] = allChats[serverId] || [];
          localStorage.setItem('allChats', JSON.stringify(allChats));
        } catch (e) {
          console.warn('Failed to init local snapshot for server chat', e);
        }
        if (typeof fetchAllChats === 'function') fetchAllChats();
        return serverId;
      }
    }

    const res = await fetch(window.buildApiUrl(`/api/chat`),{
      method: 'POST',
      headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' }
    });
    if (res.ok) {
      const chat = await res.json();
      if (chat && chat.id) {
        const serverId = chat.id;
        currentChatID = serverId;
        history.pushState({}, '', `?chatid=${serverId}`);
        try {
          const allChats = JSON.parse(localStorage.getItem('allChats') || '{}');
          allChats[serverId] = allChats[serverId] || [];
          localStorage.setItem('allChats', JSON.stringify(allChats));
        } catch (e) {
          console.warn('Failed to init local snapshot for server chat', e);
        }
        if (typeof fetchAllChats === 'function') fetchAllChats();
        return serverId;
      }
    } else {
      console.warn('Server create chat failed:', res.status, res.statusText);
    }
  } catch (err) {
    console.warn('Server unavailable, falling back to local chat creation:', err);
  }

  const newChatID = `chat_${Date.now()}`;
  currentChatID = newChatID;

  try {
    const allChats = JSON.parse(localStorage.getItem('allChats') || '{}');
    allChats[newChatID] = [];
    localStorage.setItem('allChats', JSON.stringify(allChats));
  } catch (e) {
    console.warn('Failed to create local chat snapshot', e);
  }

  history.pushState({}, '', `?chatid=${newChatID}`);

  if (typeof fetchAllChats === 'function') {
    fetchAllChats();
  }
  return newChatID;
}

let activeTypingAnimation = null;
let previousMode = 'explanation';

async function sendPrompt(chatId, promptText, inputElement, autoGenerated = false) {
  const container = document.querySelector('div.message-container');
  if (container) {
    const newChatBlock = container.querySelector('.new-chat-container, .tutor-welcome');
    if (newChatBlock) {
      container.innerHTML = '';
      container.style.display = 'flex';
      container.style.flexDirection = 'column';
      container.style.alignItems = 'stretch';
      container.style.justifyContent = 'flex-start';
      container.style.minHeight = 'auto';
      container.style.padding = '20px';
      container.style.paddingTop = '88px';
      container.style.background = 'transparent';
    }
  }

  const allChats = JSON.parse(localStorage.getItem('allChats') || '{}');
  const messages = allChats[chatId] || [];
  if (!allChats[chatId]) allChats[chatId] = messages;

  if (!autoGenerated) {
    const userMsg = { _id: window.makeId(), type: 'text', content: promptText, isModelMessage: false };
    messages.push(userMsg);

    if (window.upsertMessageDom) {
      window.upsertMessageDom(userMsg);
    }
  }

  const aiMessage = {
    _id: window.makeId(),
    type: 'text',
    content: '⏳ Processing...',
    isModelMessage: true,
  };
  messages.push(aiMessage);

  localStorage.setItem('allChats', JSON.stringify(allChats));

  if (window.upsertMessageDom) {
    window.upsertMessageDom(aiMessage);
  } else {
    console.error('Critical error: window.upsertMessageDom not found. Check js/chat.js');
    if (typeof fetchChatMessages === 'function') fetchChatMessages(chatId);
  }

  if (container) {
    container.style.paddingBottom = '120px';
    window.scrollTo(0, document.body.scrollHeight);
  }

  try {
    const mode = (typeof window.getCurrentMode === 'function')
      ? window.getCurrentMode()
      : 'explanation';

    console.log('Sending prompt with mode:', mode);

    const res = await fetch(window.buildApiUrl(`/api/chat/message`), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        chatId: chatId,
        message: promptText,
        mode: mode
      })
    });

    if (!res.ok) {
      throw new Error(`Server returned ${res.status}: ${res.statusText}`);
    }

    const data = await res.json();

    if (data.success && data.response) {
      const fullResponse = data.response;

      if (activeTypingAnimation) {
        activeTypingAnimation.cancel();
      }

      if (mode === 'testing') {
        aiMessage.content = fullResponse;
        localStorage.setItem('allChats', JSON.stringify(allChats));
        if (window.updateMessageDomContent) {
          window.updateMessageDomContent(aiMessage._id, aiMessage.content);
        }
        if (inputElement) {
          inputElement.disabled = false;
          inputElement.placeholder = 'Type your answer...';
          inputElement.focus();
        }
      } else {
        activeTypingAnimation = animateTyping(aiMessage, fullResponse, allChats, () => {
          activeTypingAnimation = null;
          if (inputElement) {
            inputElement.disabled = false;
            inputElement.placeholder = 'Ask anything...';
            inputElement.focus();
          }
        });
      }

    } else {
      aiMessage.content = 'Error: ' + (data.error || 'Unknown error');
      localStorage.setItem('allChats', JSON.stringify(allChats));
      if (window.updateMessageDomContent) {
        window.updateMessageDomContent(aiMessage._id, aiMessage.content);
      }
      if (inputElement) {
        inputElement.disabled = false;
        inputElement.placeholder = 'Ask anything...';
        inputElement.focus();
      }
    }

  } catch (error) {
    console.error('Error sending message:', error);
    aiMessage.content = '❌ Failed to connect to server.';
    localStorage.setItem('allChats', JSON.stringify(allChats));
    if (window.updateMessageDomContent) {
      window.updateMessageDomContent(aiMessage._id, aiMessage.content);
    }
    if (inputElement) {
      inputElement.disabled = false;
      inputElement.placeholder = 'Ask anything...';
    }
  }
}

function animateTyping(aiMessage, fullText, allChats, onComplete) {
  let currentIndex = 0;
  let cancelled = false;

  const CHARS_PER_INTERVAL = 1;
  const INTERVAL_MS = 10;

  aiMessage.content = '';

  const interval = setInterval(() => {
    if (cancelled) {
      clearInterval(interval);
      return;
    }

    const nextIndex = Math.min(currentIndex + CHARS_PER_INTERVAL, fullText.length);
    aiMessage.content = fullText.substring(0, nextIndex);
    currentIndex = nextIndex;

    localStorage.setItem('allChats', JSON.stringify(allChats));

    if (window.updateMessageDomContent) {
      window.updateMessageDomContent(aiMessage._id, aiMessage.content);
    }

    if (currentIndex >= fullText.length) {
      clearInterval(interval);
      if (onComplete) {
        onComplete();
      }
    }
  }, INTERVAL_MS);

  return {
    cancel: () => {
      cancelled = true;
      clearInterval(interval);
      aiMessage.content = fullText;
      localStorage.setItem('allChats', JSON.stringify(allChats));
      if (window.updateMessageDomContent) {
        window.updateMessageDomContent(aiMessage._id, aiMessage.content);
      }
      if (onComplete) {
        onComplete();
      }
    }
  };
}

async function generateChatTitle(chatId, promptText) {
  console.log(`Triggering title generation for chat ${chatId}...`);
  try {
    const res = await fetch(window.buildApiUrl(`/api/chat/${chatId}/title`), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({ prompt: promptText })
    });

    if (res.ok) {
      console.log(`Title generated for ${chatId}. Refreshing sidebar...`);
      if (typeof fetchAllChats === 'function') {
        fetchAllChats();
      }
    } else {
      console.warn('Server failed to generate chat title:', res.statusText);
    }
  } catch (err) {
    console.error('Error calling title generation API:', err);
  }
}

async function setChatTitleStatic(chatId, title) {
  console.log(`Statically setting title for chat ${chatId} to "${title}"`);
  try {
    const res = await fetch(window.buildApiUrl(`/api/chat/${chatId}/title`),  {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({ title: title })
    });

    if (res.ok) {
      console.log(`Title set for ${chatId}. Refreshing sidebar...`);
      if (typeof fetchAllChats === 'function') {
        fetchAllChats();
      }
    } else {
      console.warn('Server failed to set chat title:', res.statusText);
    }
  } catch (err) {
    console.error('Error calling set title API:', err);
  }
}

async function isChatFresh(chatId) {
  if (!chatId || chatId === 'new') return true;

  try {
    const allChats = JSON.parse(localStorage.getItem('allChats') || '{}');
    if (allChats[chatId] && allChats[chatId].length > 0) return false;
  } catch (e) {
  }

  try {
    const res = await fetch(window.buildApiUrl(`/api/fetchChat/${chatId}`),  {
      method: 'GET',
      headers: { 'Accept': 'application/json' }
    });
    if (res.ok) {
      const chat = await res.json();
      const msgs = chat.messages || [];
      return msgs.length === 0;
    }
  } catch (e) {
    console.warn('isChatFresh: fallback server check failed, assuming fresh', e);
    return true;
  }

  return true;
}

function setupModeChangeListener() {
  if (typeof window.getCurrentMode === 'function') {
    setInterval(() => {
      const currentMode = window.getCurrentMode();

      if (currentMode === 'testing' && previousMode !== 'testing') {
        console.log('Switched to testing mode - auto-generating first question');

        const chatId = currentChatID;
        if (chatId && chatId !== 'new') {
          const input = document.querySelector('chat-input input');

          if (input) {
            input.disabled = true;
            input.placeholder = 'AI is generating a test...';
          }

          sendPrompt(chatId, 'Start testing', input, true);
        }
      }

      previousMode = currentMode;
    }, 500);
  }
}

component('chat-input', (node) => {
  const logoSources = {
    light: 'icon/icon-light.png',
    dark: 'icon/icon-dark.png',
  };

  const resolveTheme = () => (document.body.classList.contains('dark-theme') ? 'dark' : 'light');
  createNode('img', node, img => {
    img.classList.add('chat-input-logo');
    img.alt = 'AI Tutor';

    const applyLogo = (theme) => {
      const normalized = theme === 'dark' ? 'dark' : 'light';
      img.src = logoSources[normalized] || logoSources.light;
    };

    applyLogo(resolveTheme());

    document.addEventListener('themechange', (event) => {
      const theme = event?.detail?.theme || resolveTheme();
      applyLogo(theme);
    });
  });

  createNode('input', node, input => {
    input.type = 'text';
    input.placeholder = 'Ask anything...';

    input.onkeydown = async (e) => {
      if (e.key === 'Enter' && input.value.trim() && !input.disabled) {
        let chatId = currentChatID;
        const promptValue = input.value;
        input.value = '';
        input.disabled = true;
        input.placeholder = 'AI is thinking...';

        const isNewChat = await isChatFresh(chatId);

        if (isNewChat && (!chatId || chatId === "new")) {
          chatId = await createNewChat();
        }

        sendPrompt(chatId, promptValue, input, false);

        if (isNewChat && chatId) {
          generateChatTitle(chatId, promptValue);
        }
      }
    };
  });

  createNode('span', node, span => {
    span.id = 'upload-trigger-button';
    span.className = 'upload-icon';
    span.innerHTML = '+';
  });
});

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', setupModeChangeListener);
} else {
  setupModeChangeListener();
}

window.createNewChat = createNewChat;
window.setChatTitleStatic = setChatTitleStatic;
